# wahoo!
# default config (default.toml)

[ui]

allow_coloring = true

[colors]

# use ANSI escape codes for this

error = "\u001b[31m" # red
success = "\u001b[32m" # green
message = "\u001b[97m" # white
warning = "\u001b[33m" # yellow
prompt = "\u001b[34m" # blue
