name: Build and update .SRCINFO
# i only made this because i wrote wahoo in windows and can't build it so uhhhh
# github actions saves the day!

on:
  push:
    branches:
      - main
    paths:
      - 'PKGBUILD'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # you cannot escape canonical

    steps:
      - name: Get repo files (with checkout)
        uses: actions/checkout@v3

      - name: Set up Arch container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/repo --rm
          run: |
            pacman -Sy --noconfirm base-devel git pacman-contrib
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chown -R builder:builder /repo
            sudo -u builder bash -c "cd /repo && \
            updpkgsums && \
            makepkg --printsrcinfo > .SRCINFO && \
            cat .SRCINFO"
      # update: added 'updpkgsums' which will update the sha256 checksums in the PKGBUILD. thank you github actions :D

      - name: Fix git permissions # multiple times i had an error just because i forgot to add this
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Commit and push .SRCINFO and PKGBUILD if changed
        run: |
          cd ${{ github.workspace }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          if ! git diff --cached --quiet; then
            git commit -m "GitHub Actions: Update .SRCINFO and PKGBUILD"
            git push origin HEAD || { echo "Push failed."; exit 255; }
          else
            echo "No changes in .SRCINFO, not commiting."
          fi
      # update: changed 'git add .SRCINFO' to 'git add -u'
      ## damn the bot writes better commit messages than me (i don't even write commit messages lmao)

# done
